// <auto-generated />
using TPTE02_Cadastro_Com_Banco.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TPTE02_Cadastro_Com_Banco.Data;

#nullable disable

namespace TPTE02_Cadastro_Com_Banco.Migrations
{
    [DbContext(typeof(ProdutoContext))]
    [Migration("20240312125555_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("TPTE02_Cadastro_Com_Banco.Model.TodoItemModel", b =>
                {
                    b.Property<long>("TodoItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("TodoItemID");

                    b.ToTable("TodoItems");
                });
#pragma warning restore 612, 618
        }
    }
}
